# Generated by Django 2.0.9 on 2018-12-09 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encargado_servicio',
            name='servicio',
        ),
    ]
