# Generated by Django 2.0.9 on 2018-12-11 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181210_1834'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encargado_servicio',
            name='servicio',
        ),
        migrations.AddField(
            model_name='encargado_servicio',
            name='division',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Division'),
        ),
    ]
