# Generated by Django 2.0.9 on 2018-12-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicio_encargado'),
        ('users', '0002_remove_encargado_servicio_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargado_servicio',
            name='division',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Division'),
        ),
    ]
