# Generated by Django 2.0.9 on 2018-11-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('duracion', models.DurationField()),
                ('capacidad', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='')),
                ('divisiones', models.ManyToManyField(to='core.Division')),
            ],
        ),
    ]
