# Generated by Django 2.0.9 on 2018-11-26 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181125_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Campus')),
            ],
        ),
    ]
